import {strings,steps,defaultTemplates} from './i18n.mjs';
const $=s=>document.querySelector(s), demo=document.body.dataset.demo==='true';
let lang=localStorage.getItem('elo-language')||((navigator.language||'').startsWith('es')?'es':'pt');
if(!strings[lang])lang='pt';
const t=k=>strings[lang][k]||k;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={today:'M8 2v4m8-4v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2zm3 11h2m4 0h2',clients:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m20 0v-2a4 4 0 0 0-3-3.87M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm8-7a4 4 0 0 1 0 8',messages:'M21 11a8 8 0 0 1-8 8H7l-5 3 2-6a8 8 0 0 1-1-4 9 9 0 1 1 18-1zM8 11h8m-8 4h5',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8zm0-6v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',plus:'M12 5v14M5 12h14',check:'m5 12 4 4L19 6',arrow:'M7 17 17 7M7 7h10v10',search:'M21 21l-5-5m2-6a7 7 0 1 1-14 0 7 7 0 0 1 14 0z',close:'m6 6 12 12M6 18 18 6',copy:'M9 9h12v12H9zM5 15H3V3h12v2',cloud:'M6 18a5 5 0 0 1-1-10 7 7 0 0 1 13-2 6 6 0 0 1 0 12M9 13l3 3 4-5',download:'M12 3v12m-4-4 4 4 4-4M4 17v4h16v-4',group:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m20 0v-2a4 4 0 0 0-3-3.87M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm8-7a4 4 0 0 1 0 8',link:'m10 13 4-4m-6 7-2 2a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m2 1 2-2a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.check}"/></svg>`;
const brand=()=>`<span class="brand"><img src="./elo/logo.svg" alt="">elo<small>CRM</small></span>`;
const locale=()=>lang==='pt'?'pt-BR':'es';
const day=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const add=(ds,n)=>{const d=new Date(ds+'T12:00:00');d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const fmt=ds=>new Intl.DateTimeFormat(locale(),{day:'2-digit',month:'short'}).format(new Date(ds+'T12:00:00'));
const initials=n=>n.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const stepLabel=s=>s.days<60?`${t('days')} ${s.days}`:`${s.days/30} ${t('months')}`;
let view='today',search='',user=demo?{uid:'demo',email:'demo@elo.example',displayName:'Rafael'}:null,showLogin=false;
let clients=[],templates={},store=null,syncState='loading',ready=demo;
if(demo){clients=[
 {id:'demo1',name:'Mariana e Pedro',phone:'+5548999990001',saleDate:add(day(),-1),product:'Costão Estaleirinho',notes:'Casal com dois filhos. Querem aproveitar as férias em família. Preferem conversar pelo grupo.',destino:'Bariloche',destino2:'Orlando',name2:'Pedro',phone2:'+5548999990002',channel:'group',groupName:'Família Oliveira · Costão',sent:{},skipped:{}},
 {id:'demo2',name:'Ana e Ricardo',phone:'+5548999990003',saleDate:add(day(),-8),product:'Costão Estaleirinho',notes:'Sonham em conhecer a Europa.',destino:'Lisboa',destino2:'Roma',channel:'group',groupName:'Família Santos · Costão',sent:{d1:add(day(),-7)},skipped:{}},
 {id:'demo3',name:'Camila Ferreira',phone:'+5548999990004',saleDate:add(day(),-13),product:'Costão Estaleirinho',destino:'Gramado',sent:{d1:add(day(),-12),d7:day()},skipped:{}},
 {id:'demo4',name:'Lucas e Beatriz',phone:'+5548999990005',saleDate:add(day(),-27),product:'Costão Estaleirinho',destino:'Santiago',sent:{d1:add(day(),-26),d7:add(day(),-19),d15:day()},skipped:{}}
 ];}
function tpl(key){const saved=templates[key];return typeof saved==='string'?{text:saved,media:''}:saved||defaultTemplates(lang)[key];}
function message(c,key,name){return (tpl(key).text||'').replace(/\{(nome|vendedor|produto|destino2|destino)\}/g,(_,k)=>({nome:name||c.name,vendedor:user?.displayName||user?.email?.split('@')[0]||'',produto:c.product||'',destino:c.destino||'',destino2:c.destino2||c.destino||''}[k]));}
function fullMessage(c,key,name){return message(c,key,name)+(tpl(key).media?'\n\n'+tpl(key).media:'');}
function validUrl(v,group=false){try{const u=new URL(v);return u.protocol==='https:'&&(!group||u.hostname==='chat.whatsapp.com')?u.href:null;}catch{return null;}}
function wa(c,key,second=false){let num=(second?c.phone2:c.phone).replace(/\D/g,'');if(!(second?c.phone2:c.phone).startsWith('+')&&(num.length===10||num.length===11))num='55'+num;return `https://wa.me/${num}?text=${encodeURIComponent(fullMessage(c,key,second?c.name2:undefined))}`;}
const btn=(key,action,cls='',ico='')=>`<button type="button" class="btn ${cls}" data-action="${action}">${ico?icon(ico):''}${t(key)}</button>`;
function language(){return `<select class="language" data-language aria-label="${t('language')}"><option value="pt" ${lang==='pt'?'selected':''}>Português</option><option value="es" ${lang==='es'?'selected':''}>Español</option></select>`;}
function pending(){return clients.flatMap(c=>steps.filter(s=>add(c.saleDate,s.days)<=day()&&!c.sent?.[s.key]&&!c.skipped?.[s.key]).map(s=>({c,s}))).sort((a,b)=>add(a.c.saleDate,a.s.days).localeCompare(add(b.c.saleDate,b.s.days)));}
function status(s,c){return c.sent?.[s.key]?'done':c.skipped?.[s.key]?'skipped':add(c.saleDate,s.days)<=day()?'due':'scheduled';}
function toast(k){const el=$('#toast');el.textContent=t(k);el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,4500);}
function title(titleKey,subKey,create=true){return `<div class="page-heading"><div>${view==='today'?`<div class="eyebrow">${new Intl.DateTimeFormat(locale(),{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</div>`:''}<h1>${t(titleKey)}</h1><p>${t(subKey)}</p></div>${create?btn('new','new','primary','plus'):''}</div>`;}
function render(){document.documentElement.lang=locale();document.title='Elo CRM';if(!user||showLogin){renderLogin();return;}
const p=pending();$('#app').innerHTML=`${demo?`<div class="demo-banner">${t('demo')}<button data-action="loginView">${t('loginView')}</button></div>`:''}<div class="shell"><aside class="sidebar">${brand()}<div class="nav-label">${t('workspace')}</div><nav class="nav" aria-label="${t('workspace')}">${['today','clients','messages','settings'].map(v=>`<button data-view="${v}" class="${view===v?'active':''}" ${view===v?'aria-current="page"':''}>${icon(v)}<span>${t(v)}</span>${v==='today'&&p.length?`<span class="count">${p.length}</span>`:''}</button>`).join('')}</nav><div class="sidebar-foot"><div class="profile"><span class="avatar">${esc(initials(user.displayName||user.email))}</span><div><strong>${esc(user.displayName||user.email.split('@')[0])}</strong><small>${t('seller')}</small></div></div></aside><header class="topbar"><span class="mobile-brand">${brand()}</span><div class="breadcrumb">Elo CRM <span aria-hidden="true"> / </span> <b>${t(view==='new'?'new':view)}</b></div><div class="top-actions"><span id="sync-status" class="sync" role="status"></span>${language()}</div></header><main class="content" id="main">${!ready?`<div class="empty"><h2>${t('loading')}</h2><p>${t('noCache')}</p></div>`:page()}</main></div>`;renderSync();}
function renderSync(){const el=$('#sync-status');if(!el)return;el.dataset.state=syncState;el.textContent=demo?t('demoState'):t({saved:'syncSaved',pending:'syncPending',offline:'syncOffline',error:'syncError',loading:'syncLoading'}[syncState]);}
function task({c,s}){return `<article class="task-card"><div class="card-head"><span class="avatar">${esc(initials(c.name))}</span><div class="person"><h3>${esc(c.name)}</h3><p>${esc(c.channel==='group'?c.groupName:c.product)}</p></div><span class="pill due">${stepLabel(s)} · ${t(s.title)}</span></div><div class="message">${esc(message(c,s.key))}</div>${tpl(s.key).media&&validUrl(tpl(s.key).media)?`<p class="hint"><a target="_blank" rel="noopener noreferrer" href="${esc(validUrl(tpl(s.key).media))}">${t('openMedia')} ↗</a></p>`:''}<div class="card-foot"><div class="actions">${c.channel==='group'?btn('copy',`copy:${c.id}:${s.key}`,'soft','copy'):`<a class="btn soft" href="${demo?'#':esc(wa(c,s.key))}" ${demo?'data-action="demoWhatsApp"':'target="_blank" rel="noopener noreferrer"'}>${icon('messages')}${t('openWhatsApp')}</a>`}${c.channel==='group'&&validUrl(c.groupUrl,true)?`<a class="btn" target="_blank" rel="noopener noreferrer" href="${esc(validUrl(c.groupUrl,true))}">${icon('arrow')}${t('openGroup')}</a>`:''}${c.channel!=='group'&&c.phone2?`<a class="btn" href="${demo?'#':esc(wa(c,s.key,true))}" ${demo?'data-action="demoWhatsApp"':'target="_blank" rel="noopener noreferrer"'}>${esc(c.name2||t('second'))} ↗</a>`:''}</div><div class="actions"><button class="text-button" data-action="skip:${c.id}:${s.key}">${t('skip')}</button><button class="btn" data-action="sent:${c.id}:${s.key}" title="${t('confirmHint')}">${icon('check')}${t('confirm')}</button></div></div>${c.channel==='group'?`<p class="small muted" style="margin-top:12px">${t('groupHint')}</p>`:''}</article>`;}
function page(){if(view==='new')return title('new','newSub',false)+clientForm();if(view==='clients')return title('clients','clientsSub')+`<div class="search">${icon('search')}<input id="search" type="search" placeholder="${t('search')}" value="${esc(search)}" aria-label="${t('search')}"></div><div class="clients" id="client-list">${clientList()}</div>`;
if(view==='messages')return title('messages','messagesSub',false)+`<p class="hint">${t('variables')}: <code>{nome}</code> <code>{vendedor}</code> <code>{produto}</code> <code>{destino}</code> <code>{destino2}</code><br>${t('templateNote')}</p><div class="templates">${steps.map(s=>`<article class="template"><span class="pill">${stepLabel(s)}</span><h3>${t(s.title)}</h3><div class="message">${esc(tpl(s.key).text)}</div>${btn('edit','template:'+s.key,'','messages')}</article>`).join('')}</div>`;
if(view==='settings')return title('settings','settingsSub',false)+`<div class="settings"><section class="form-panel"><h2>${t('account')}</h2><p>${esc(user.email)}</p><form id="profile-form"><label class="field" style="margin-top:20px">${t('displayName')}<input name="displayName" value="${esc(user.displayName||'')}" required maxlength="80"></label><div class="form-actions"><button class="btn primary">${t('save')}</button></div></form><div class="settings-row"><span>${t('language')}</span>${language()}</div></section><section class="form-panel"><h2>${t('data')}</h2><div class="settings-row"><div>${t('automatic')}<small>${demo?t('demoNote'):t('sync'+({saved:'Saved',pending:'Pending',offline:'Offline',loading:'Loading',error:'Error'}[syncState]))}</small></div></div><div class="settings-row"><div>${t('backup')}<small>${t('backupPending')}</small></div></div>${btn('export','export','','download')}</section><div>${btn('logout','logout','danger')}</div></div>`;
const p=pending(),next=clients.flatMap(c=>steps.filter(s=>add(c.saleDate,s.days)>day()&&!c.sent?.[s.key]&&!c.skipped?.[s.key]).map(s=>({c,s,date:add(c.saleDate,s.days)}))).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4);
return title('today','todaySub')+`<div class="stats">${[['pending',p.length,'contacts','messages'],['customers',clients.length,'registered','clients'],['done',clients.reduce((n,c)=>n+Object.values(c.sent||{}).filter(d=>d===day()).length,0),'sent','check']].map(([label,value,sub,ico])=>`<div class="stat"><div class="stat-top">${t(label)}${icon(ico)}</div><strong>${value.toString().padStart(2,'0')}</strong><small>${t(sub)}</small></div>`).join('')}</div><div class="workspace"><section><div class="section-head"><h2>${t('agenda')}</h2><span>${p.length} ${t('contacts')}</span></div>${p.length?p.map(task).join(''):`<div class="empty">${icon('check')}<h3>${t(clients.length?'allClear':'empty')}</h3><p>${t(clients.length?'allClearSub':'emptySub')}</p></div>`}</section><aside><div class="aside-box"><h3>${t('next')}</h3><p>${t('nextSub')}</p>${next.length?next.map(({c,s,date})=>`<div class="upcoming"><div class="datebox"><b>${date.slice(-2)}</b><small>${new Intl.DateTimeFormat(locale(),{month:'short'}).format(new Date(date+'T12:00:00'))}</small></div><div><strong>${esc(c.name)}</strong><p>${t(s.title)}</p></div></div>`).join(''):`<p style="margin-top:20px">${t('emptyNext')}</p>`}</div><p class="quiet-note">${icon('cloud')}${demo?t('demoNote'):t('automatic')}</p></aside></div><p class="footer-caption">ELO CRM · ${t('subject').toUpperCase()}</p>`;}
function clientList(){const q=search.trim().toLocaleLowerCase(),digits=q.replace(/\D/g,'');return clients.filter(c=>!q||[c.name,c.name2,c.product,c.notes,c.groupName].some(v=>(v||'').toLocaleLowerCase().includes(q))||(digits&&[c.phone,c.phone2].some(v=>(v||'').replace(/\D/g,'').includes(digits)))).map(c=>`<button class="client" data-action="detail:${c.id}"><div class="card-head"><span class="avatar">${esc(initials(c.name))}</span><div class="person"><h3>${esc(c.name)}</h3><p>${esc(c.phone)}</p></div>${icon(c.channel==='group'?'group':'arrow')}</div><p class="product">${esc(c.product||'—')} · ${fmt(c.saleDate)}</p><div class="timeline">${steps.map(s=>`<span class="pill ${status(s,c)}">${c.sent?.[s.key]?'✓ ':''}${stepLabel(s)}</span>`).join('')}</div></button>`).join('')||`<div class="empty"><h3>${t('empty')}</h3></div>`;}
function field(key,name,value='',type='text',full=false,required=false){return `<label class="field ${full?'full':''}">${t(key)}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} maxlength="${name==='groupUrl'?500:180}"></label>`;}
function clientForm(c={}){return `<form id="client-form" data-id="${esc(c.id||'')}" data-base="${esc(JSON.stringify(c))}" class="form-panel"><div class="form-grid">${field('name','name',c.name,'text',false,true)}${field('phone','phone',c.phone,'tel',false,true)}${field('date','saleDate',c.saleDate||day(),'date',false,true)}${field('product','product',c.product)}<div class="form-divider">${t('destination')}</div><label class="field">${t('destination')}<select name="channel" id="channel"><option value="individual" ${c.channel!=='group'?'selected':''}>${t('individual')}</option><option value="group" ${c.channel==='group'?'selected':''}>${t('group')}</option></select></label>${field('groupName','groupName',c.groupName)}${field('groupUrl','groupUrl',c.groupUrl,'url',true)}<p class="field full muted small">${t('groupHint')}</p><div class="form-divider">${t('notes')}</div><label class="field full">${t('notes')}<textarea name="notes" maxlength="12000" placeholder="${t('notesHint')}">${esc(c.notes||'')}</textarea></label>${field('dream','destino',c.destino)}${field('dream2','destino2',c.destino2)}<div class="form-divider">${t('second')}</div>${field('name2','name2',c.name2)}${field('phone2','phone2',c.phone2,'tel')}</div><div class="form-actions">${btn('cancel',c.id?'close':'today','ghost')}<button type="submit" class="btn primary">${icon('check')}${t('save')}</button></div></form>`;}
function modal(heading,body){$('#dialog').innerHTML=`<div class="dialog-head"><h2>${esc(heading)}</h2><button class="btn icon ghost" data-action="close" aria-label="${t('close')}">${icon('close')}</button></div><div class="dialog-body">${body}</div>`;if(!$('#dialog').open)$('#dialog').showModal();}
function detail(c){modal(c.name,`<div class="card-head"><span class="avatar">${esc(initials(c.name))}</span><div class="person"><h3>${esc(c.product||'—')}</h3><p>${esc(c.phone)} · ${fmt(c.saleDate)}</p></div>${btn('edit','edit:'+c.id)}</div>${c.channel==='group'?`<p class="hint" style="margin-top:20px">${icon('group')} ${esc(c.groupName)}</p>`:''}${c.notes?`<div class="detail-notes">${esc(c.notes)}</div>`:''}<p class="hint">${esc([c.destino,c.destino2].filter(Boolean).join(' · '))}</p>${steps.map(s=>`<div class="timeline-row"><div><span class="pill ${status(s,c)}">${stepLabel(s)}</span> <span class="small">${t(s.title)} · ${fmt(add(c.saleDate,s.days))}</span></div>${c.sent?.[s.key]||c.skipped?.[s.key]?btn('undo',`undo:${c.id}:${s.key}`,'ghost'):btn('copy',`copy:${c.id}:${s.key}`,'ghost','copy')}</div>`).join('')}<div class="form-actions">${btn('delete','delete:'+c.id,'danger')}</div>`);}
function renderLogin(){document.documentElement.lang=locale();$('#app').innerHTML=`<section class="login"><div class="login-story">${brand()}<div><h1>${t('loginHero')}</h1><p>${t('loginStory')}</p></div><small class="muted">ELO CRM</small><img class="watermark" src="./elo/logo.svg" alt=""></div><div class="login-form-wrap">${language()}<div class="login-form"><h2>${t('loginTitle')}</h2><p>${t('loginSubtitle')}</p><form id="login-form"><label class="field">${t('email')}<input name="email" id="email" type="email" autocomplete="username" required></label><label class="field">${t('password')}<input name="password" type="password" autocomplete="current-password" required></label><button class="btn primary" id="login-button">${t('login')}${icon('arrow')}</button></form><button type="button" class="reset" data-action="reset" id="reset-button">${t('reset')}</button><div id="auth-feedback" class="feedback" role="status"></div><p class="login-foot">${demo?t('demoNote'):t('privacy')}</p>${demo?`<button class="reset" data-action="backDemo">${t('backDemo')}</button>`:''}</div></div></section>`;}
async function save(op){try{if(demo){if(op.kind==='delete')clients=clients.filter(c=>c.id!==op.id);else if(op.kind==='template')templates[op.id]={...tpl(op.id),...op.patch};else if(op.kind==='add')clients.push(op.client);else{const c=clients.find(c=>c.id===op.id);if(c){if(op.kind==='step'){c.sent??={};c.skipped??={};delete c.sent[op.key];delete c.skipped[op.key];if(op.state!=='undo')c[op.state==='sent'?'sent':'skipped'][op.key]=day();}else Object.assign(c,op.patch);}}}else await store.enqueue(op);return true;}catch(e){toast('localError');return false;}}
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;$('#client-list').innerHTML=clientList();}});
document.addEventListener('change',e=>{if(e.target.matches('[data-language]')){lang=e.target.value;try{localStorage.setItem('elo-language',lang);}catch{}if(window.firebase?.auth)firebase.auth().languageCode=locale();$('#dialog').close();render();}});
document.addEventListener('click',async e=>{const v=e.target.closest('[data-view]');if(v){view=v.dataset.view;render();return;}const el=e.target.closest('[data-action]');if(!el)return;const [action,id,key]=el.dataset.action.split(':');const c=clients.find(c=>c.id===id);
if(action==='new'||action==='today'){view=action;render();}else if(action==='close')$('#dialog').close();else if(action==='loginView'){showLogin=true;render();}else if(action==='backDemo'){showLogin=false;render();}else if(action==='detail'&&c)detail(c);else if(action==='edit'&&c)modal(t('edit'),clientForm(c));else if(action==='template')modal(t(steps.find(s=>s.key===id).title),`<form id="template-form" data-id="${id}"><label class="field">${t('messages')}<textarea name="text" rows="8" maxlength="12000" required>${esc(tpl(id).text)}</textarea></label><label class="field" style="margin-top:18px">${t('media')}<input type="url" name="media" value="${esc(tpl(id).media)}"></label><div class="form-actions"><button class="btn primary">${t('save')}</button></div></form>`);
else if(action==='copy'&&c){try{await navigator.clipboard.writeText(fullMessage(c,key));toast('copied');}catch{modal(t('copy'),`<p class="hint">${t('copyError')}</p><textarea style="width:100%;min-height:200px" readonly>${esc(fullMessage(c,key))}</textarea>`);}}else if(['sent','skip','undo'].includes(action)&&c){if(await save({kind:'step',id,key,state:action,date:day()})){if($('#dialog').open)detail(clients.find(x=>x.id===id));render();}}
else if(action==='delete'&&c){modal(t('deleteAsk'),`<p class="hint">${esc(c.name)}<br>${t('removeConfirm')}</p><div class="form-actions">${btn('cancel','close')}${btn('delete','confirmDelete:'+id,'danger')}</div>`);}else if(action==='confirmDelete'){if(await save({kind:'delete',id})){$('#dialog').close();render();}}
else if(action==='logout'){if(store?.pendingCount){toast('pendingLogout');return;}if(demo){showLogin=true;render();}else await firebase.auth().signOut();}else if(action==='export')exportCSV();else if(action==='reset')resetPassword();else if(action==='demoWhatsApp'){e.preventDefault();toast('demoNote');}});
document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f));if(f.id==='client-form'){for(const k in d)d[k]=d[k].trim();if(d.channel==='group'&&!d.groupName){toast('groupMissing');return;}if(d.groupUrl&&!validUrl(d.groupUrl,true)){toast('invalidLink');return;}const id=f.dataset.id;const base=JSON.parse(f.dataset.base||'{}');const patch=Object.fromEntries(Object.entries(d).filter(([k,v])=>v!==(base[k]||'')));const op=id?{kind:'patch',id,patch}:{kind:'add',client:{...d,id:crypto.randomUUID(),sent:{},skipped:{},createdAt:day()}};if(await save(op)){$('#dialog').close();view='clients';render();toast('saved');}}
else if(f.id==='template-form'){if(d.media&&!validUrl(d.media)){toast('invalidLink');return;}if(await save({kind:'template',id:f.dataset.id,patch:d})){$('#dialog').close();render();}}
else if(f.id==='profile-form'){if(demo)user.displayName=d.displayName;else{try{await user.updateProfile({displayName:d.displayName});}catch{toast('syncError');return;}}render();}
else if(f.id==='login-form'){if(demo){showLogin=false;render();return;}const b=$('#login-button');b.disabled=true;b.textContent=t('entering');try{await firebase.auth().signInWithEmailAndPassword(d.email.trim(),d.password);}catch(err){$('#auth-feedback').textContent=t(err.code==='auth/network-request-failed'?'network':'authError');}finally{if(b.isConnected){b.disabled=false;b.textContent=t('login');}}}});
async function resetPassword(){const email=$('#email');if(!email.value.trim()||!email.checkValidity()){email.reportValidity();$('#auth-feedback').textContent=t('invalid');return;}if(demo){$('#auth-feedback').textContent=t('demoNote');return;}const b=$('#reset-button'),feedback=$('#auth-feedback');b.disabled=true;b.textContent=t('sending');feedback.textContent='';try{firebase.auth().languageCode=locale();await firebase.auth().sendPasswordResetEmail(email.value.trim());feedback.classList.add('ok');feedback.textContent=t('resetSuccess');}catch(err){feedback.classList.remove('ok');feedback.textContent=t(err.code==='auth/network-request-failed'?'network':err.code==='auth/too-many-requests'?'rate':err.code==='auth/user-not-found'?'resetSuccess':'resetError');}finally{b.disabled=false;b.textContent=t('reset');}}
function exportCSV(){if(!clients.length){toast('exportEmpty');return;}const fields=['name','phone','saleDate','product','name2','phone2','groupName','notes','destino','destino2'];const rows=[fields,...clients.map(c=>fields.map(k=>c[k]||''))];const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`elo-clientes-${day()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
render();
if(!demo){try{const {start}=await import('./sync.mjs');firebase.initializeApp({apiKey:'AIzaSyBGSf94odnS8307MEgCiiNzuk8zzQXd4MI',authDomain:'meu-crm-4f832.firebaseapp.com',projectId:'meu-crm-4f832',appId:'1:396030774693:web:e344fda8296720a4396c4c'});firebase.auth().languageCode=locale();firebase.auth().onAuthStateChanged(async u=>{store?.stop();store=null;user=u;clients=[];templates={};ready=false;view='today';$('#dialog').close();render();if(u)store=await start(u,(data,state)=>{clients=data.clients||[];templates=data.templates||{};syncState=state;ready=data.ready;const editing=['new'].includes(view)||$('#dialog').open||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if(editing)renderSync();else render();});});}catch(e){const el=$('#auth-feedback');if(el)el.textContent=t('network');}}
